import os
class ImageDirectory:
    base_path = "img"
    auto_say_hi = os.path.join(base_path, "auto_say_hi.jpg")
    auto_car_brand = os.path.join(base_path, "auto_car_brand.jpg")
    auto_car_model = os.path.join(base_path, "auto_car_model.jpg")
    auto_car_year = os.path.join(base_path, "auto_car_year.jpg")
    auto_car_body_type = os.path.join(base_path, "auto_car_body_type.jpg")
    auto_car_engine_type = os.path.join(base_path, "auto_car_engine_type.jpg")
    auto_car_engine_volume = os.path.join(base_path, "auto_car_engine_volume.jpg")
    auto_car_power = os.path.join(base_path, "auto_car_power.jpg")
    auto_car_transmission_type = os.path.join(base_path, "auto_car_transmission_type.jpg")
    auto_car_color = os.path.join(base_path, "auto_car_color.jpg")
    auto_car_mileage = os.path.join(base_path, "auto_car_mileage.jpg")
    auto_car_document_status = os.path.join(base_path, "auto_car_document_status.jpg")
    auto_car_owners = os.path.join(base_path, "auto_car_owners.jpg")
    auto_car_customs_cleared = os.path.join(base_path, "auto_car_customs_cleared.jpg")
    auto_car_condition = os.path.join(base_path, "auto_car_condition.jpg")
    auto_car_description = os.path.join(base_path, "auto_car_description.jpg")
    auto_car_currency = os.path.join(base_path, "auto_car_currency.jpg")
    auto_car_price = os.path.join(base_path, "auto_car_price.jpg")
    auto_car_location = os.path.join(base_path, "auto_car_location.jpg")
    auto_seller_name = os.path.join(base_path, "auto_seller_name.jpg")
    auto_seller_phone = os.path.join(base_path, "auto_seller_phone.jpg")
    auto_car_photos = os.path.join(base_path, "auto_car_photos.jpg")

