import os
class ImageDirectory:
    base_path = "img"
    say_hi = os.path.join(base_path, "say_hi.jpg")
    car_brand = os.path.join(base_path, "car_brand.jpg")
    car_model = os.path.join(base_path, "car_model.jpg")
    car_year = os.path.join(base_path, "car_year.jpg")
    car_body_type = os.path.join(base_path, "car_body_type.jpg")
    car_engine_type = os.path.join(base_path, "car_engine_type.jpg")
    car_engine_volume = os.path.join(base_path, "car_engine_volume.jpg")
    car_power = os.path.join(base_path, "car_power.jpg")
    car_transmission_type = os.path.join(base_path, "car_transmission_type.jpg")
    car_color = os.path.join(base_path, "car_color.jpg")
    car_mileage = os.path.join(base_path, "car_mileage.jpg")
    car_document_status = os.path.join(base_path, "car_document_status.jpg")
    car_owners = os.path.join(base_path, "car_owners.jpg")
    car_customs_cleared = os.path.join(base_path, "car_customs_cleared.jpg")
    car_condition = os.path.join(base_path, "car_condition.jpg")
    car_description = os.path.join(base_path, "car_description.jpg")
    car_currency = os.path.join(base_path, "car_currency.jpg")
    car_price = os.path.join(base_path, "car_price.jpg")
    car_location = os.path.join(base_path, "car_location.jpg")
    seller_name = os.path.join(base_path, "seller_name.jpg")
    seller_phone = os.path.join(base_path, "seller_phone.jpg")
    car_photos = os.path.join(base_path, "car_photos.jpg")
