import os
class ImageDirectory:
    base_path = "img"
    auto_say_hi = os.path.join(base_path, "auto_say_hi.jpg")
    auto_car_brand = os.path.join(base_path, "auto_car_brand.jpg")
    auto_car_model = os.path.join(base_path, "auto_car_model.jpg")
    auto_car_year = os.path.join(base_path, "auto_car_year.jpg")
    auto_car_body_type = os.path.join(base_path, "auto_car_body_type.jpg")
    auto_car_engine_type = os.path.join(base_path, "auto_car_engine_type.jpg")
    auto_car_engine_volume = os.path.join(base_path, "auto_car_engine_volume.jpg")
    auto_car_power = os.path.join(base_path, "auto_car_power.jpg")
    auto_car_transmission_type = os.path.join(base_path, "auto_car_transmission_type.jpg")
    auto_car_color = os.path.join(base_path, "auto_car_color.jpg")
    auto_car_mileage = os.path.join(base_path, "auto_car_mileage.jpg")
    auto_car_document_status = os.path.join(base_path, "auto_car_document_status.jpg")
    auto_car_owners = os.path.join(base_path, "auto_car_owners.jpg")
    auto_car_customs_cleared = os.path.join(base_path, "auto_car_customs_cleared.jpg")
    auto_car_condition = os.path.join(base_path, "auto_car_condition.jpg")
    auto_car_description = os.path.join(base_path, "auto_car_description.jpg")
    auto_car_currency = os.path.join(base_path, "auto_car_currency.jpg")
    auto_car_price = os.path.join(base_path, "auto_car_price.jpg")
    auto_car_location = os.path.join(base_path, "auto_car_location.jpg")
    auto_seller_name = os.path.join(base_path, "auto_seller_name.jpg")
    auto_seller_phone = os.path.join(base_path, "auto_seller_phone.jpg")
    auto_car_photos = os.path.join(base_path, "auto_car_photos.jpg")
    # работа
    job_title = os.path.join(base_path, "job_title.jpg")
    job_responsibilities = os.path.join(base_path, "job_responsibilities.jpg")
    job_requirements = os.path.join(base_path, "job_requirements.jpg")
    job_condition = os.path.join(base_path, "job_condition.jpg")
    job_contacts = os.path.join(base_path, "job_contacts.jpg")
    job_photos = os.path.join(base_path, "job_photos.jpg")
    # недвижимость
    realty_deal_type = os.path.join(base_path, "realty_deal_type.jpg")
    realty_type = os.path.join(base_path, "realty_type.jpg")
    # asdasd
    realty_rooms = os.path.join(base_path, "realty_rooms.jpg")
    realty_floor = os.path.join(base_path, "realty_floor.jpg")
    realty_floors_total = os.path.join(base_path, "realty_floors_total.jpg")
    # asdasd
    realty_square = os.path.join(base_path, "realty_square.jpg")
    realty_description = os.path.join(base_path, "realty_description.jpg")
    realty_location = os.path.join(base_path, "realty_location.jpg")
    realty_currency = os.path.join(base_path, "realty_currency.jpg")
    realty_price = os.path.join(base_path, "realty_price.jpg")
    realty_photo = os.path.join(base_path, "realty_photo.jpg")
    realty_contacts = os.path.join(base_path, "realty_contacts.jpg")

